<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'email' => 'admin@cmc.edu.ph',
                'role' => 'it_admin',
                'official_id' => 'ADMIN001',
                'first_name' => 'John',
                'last_name' => 'Doe',
                'middle_name' => 'Smith',
                'phone' => '09123456789',
                'address' => '123 Main St, Quezon City',
                'date_of_birth' => '1985-05-15',
                'sex' => 'male',
            ],
            [
                'email' => 'registrar@cmc.edu.ph',
                'role' => 'registrar',
                'official_id' => 'REG001',
                'first_name' => 'Pedro',
                'last_name' => 'Cruz',
                'middle_name' => 'Reyes',
                'phone' => '09161234567',
                'address' => '789 Admin Bldg, Quezon City',
                'date_of_birth' => '1980-03-10',
                'sex' => 'male',
            ],
            [
                'email' => 'dean.coecs@cmc.edu.ph',
                'role' => 'dean',
                'official_id' => 'DEAN-COECS',
                'first_name' => 'Maria',
                'last_name' => 'Garcia',
                'middle_name' => 'Santos',
                'phone' => '09187654321',
                'address' => '456 University Ave, Quezon City',
                'date_of_birth' => '1975-08-20',
                'sex' => 'female',
            ],
            [
                'email' => 'dean.cba@cmc.edu.ph',
                'role' => 'dean',
                'official_id' => 'DEAN-CBA',
                'first_name' => 'Loren',
                'last_name' => 'Villanueva',
                'middle_name' => 'Reyes',
                'phone' => '09180001111',
                'address' => '101 Business Ave, Quezon City',
                'date_of_birth' => '1973-02-12',
                'sex' => 'female',
            ],
            [
                'email' => 'ph.bsit@cmc.edu.ph',
                'role' => 'program_head',
                'official_id' => 'PH-BSIT',
                'first_name' => 'Ana',
                'last_name' => 'Mendoza',
                'middle_name' => 'Lopez',
                'phone' => '09171234567',
                'address' => '321 Faculty St, Quezon City',
                'date_of_birth' => '1982-11-25',
                'sex' => 'female',
            ],
            [
                'email' => 'ph.bscs@cmc.edu.ph',
                'role' => 'program_head',
                'official_id' => 'PH-BSCS',
                'first_name' => 'Renato',
                'last_name' => 'Sison',
                'middle_name' => 'Cruz',
                'phone' => '09170002222',
                'address' => '322 Faculty St, Quezon City',
                'date_of_birth' => '1981-06-01',
                'sex' => 'male',
            ],
            [
                'email' => 'ph.bsba@cmc.edu.ph',
                'role' => 'program_head',
                'official_id' => 'PH-BSBA',
                'first_name' => 'Dianne',
                'last_name' => 'Rosales',
                'middle_name' => 'Torres',
                'phone' => '09170003333',
                'address' => '201 Business Ave, Quezon City',
                'date_of_birth' => '1983-04-17',
                'sex' => 'female',
            ],
            [
                'email' => 'ph.bsa@cmc.edu.ph',
                'role' => 'program_head',
                'official_id' => 'PH-BSA',
                'first_name' => 'Paolo',
                'last_name' => 'Lazaro',
                'middle_name' => 'Diaz',
                'phone' => '09170004444',
                'address' => '202 Business Ave, Quezon City',
                'date_of_birth' => '1980-09-14',
                'sex' => 'male',
            ],
            [
                'email' => 'inst.it@cmc.edu.ph',
                'role' => 'instructor',
                'official_id' => 'INST-IT',
                'first_name' => 'Rhea',
                'last_name' => 'Santos',
                'middle_name' => 'Dela Cruz',
                'phone' => '09175550001',
                'address' => '11 Faculty St, Quezon City',
                'date_of_birth' => '1987-01-19',
                'sex' => 'female',
            ],
            [
                'email' => 'inst.cs@cmc.edu.ph',
                'role' => 'instructor',
                'official_id' => 'INST-CS',
                'first_name' => 'Armand',
                'last_name' => 'Delgado',
                'middle_name' => 'Sy',
                'phone' => '09175550002',
                'address' => '12 Faculty St, Quezon City',
                'date_of_birth' => '1986-05-07',
                'sex' => 'male',
            ],
            [
                'email' => 'inst.ba@cmc.edu.ph',
                'role' => 'instructor',
                'official_id' => 'INST-BA',
                'first_name' => 'Janelle',
                'last_name' => 'Pascual',
                'middle_name' => 'Lim',
                'phone' => '09175550003',
                'address' => '21 Business Ave, Quezon City',
                'date_of_birth' => '1988-03-22',
                'sex' => 'female',
            ],
            [
                'email' => 'inst.acc@cmc.edu.ph',
                'role' => 'instructor',
                'official_id' => 'INST-ACC',
                'first_name' => 'Victor',
                'last_name' => 'Alvarez',
                'middle_name' => 'Tan',
                'phone' => '09175550004',
                'address' => '22 Business Ave, Quezon City',
                'date_of_birth' => '1984-12-02',
                'sex' => 'male',
            ],
            [
                'email' => 'student.bsit1@cmc.edu.ph',
                'role' => 'student',
                'official_id' => '2025-0001',
                'first_name' => 'Kyle',
                'last_name' => 'Reyes',
                'middle_name' => 'G.',
                'phone' => '09179990001',
                'address' => '1 Student St, Quezon City',
                'date_of_birth' => '2006-06-15',
                'sex' => 'male',
            ],
            [
                'email' => 'student.bsit2@cmc.edu.ph',
                'role' => 'student',
                'official_id' => '2025-0002',
                'first_name' => 'Mia',
                'last_name' => 'Santos',
                'middle_name' => 'L.',
                'phone' => '09179990002',
                'address' => '2 Student St, Quezon City',
                'date_of_birth' => '2006-03-09',
                'sex' => 'female',
            ],
            [
                'email' => 'student.bscs1@cmc.edu.ph',
                'role' => 'student',
                'official_id' => '2025-0003',
                'first_name' => 'Noel',
                'last_name' => 'Garcia',
                'middle_name' => 'C.',
                'phone' => '09179990003',
                'address' => '3 Student St, Quezon City',
                'date_of_birth' => '2005-10-22',
                'sex' => 'male',
            ],
            [
                'email' => 'student.bscs2@cmc.edu.ph',
                'role' => 'student',
                'official_id' => '2025-0004',
                'first_name' => 'Ivy',
                'last_name' => 'Castro',
                'middle_name' => 'M.',
                'phone' => '09179990004',
                'address' => '4 Student St, Quezon City',
                'date_of_birth' => '2005-11-30',
                'sex' => 'female',
            ],
            [
                'email' => 'student.bsba1@cmc.edu.ph',
                'role' => 'student',
                'official_id' => '2025-0005',
                'first_name' => 'Liam',
                'last_name' => 'Pena',
                'middle_name' => 'R.',
                'phone' => '09179990005',
                'address' => '5 Student St, Quezon City',
                'date_of_birth' => '2006-02-18',
                'sex' => 'male',
            ],
            [
                'email' => 'student.bsba2@cmc.edu.ph',
                'role' => 'student',
                'official_id' => '2025-0006',
                'first_name' => 'Alyssa',
                'last_name' => 'Santiago',
                'middle_name' => 'E.',
                'phone' => '09179990006',
                'address' => '6 Student St, Quezon City',
                'date_of_birth' => '2006-08-11',
                'sex' => 'female',
            ],
            [
                'email' => 'student.bsa1@cmc.edu.ph',
                'role' => 'student',
                'official_id' => '2025-0007',
                'first_name' => 'Jared',
                'last_name' => 'Dizon',
                'middle_name' => 'K.',
                'phone' => '09179990007',
                'address' => '7 Student St, Quezon City',
                'date_of_birth' => '2006-01-25',
                'sex' => 'male',
            ],
            [
                'email' => 'student.bsa2@cmc.edu.ph',
                'role' => 'student',
                'official_id' => '2025-0008',
                'first_name' => 'Celine',
                'last_name' => 'Bernardo',
                'middle_name' => 'T.',
                'phone' => '09179990008',
                'address' => '8 Student St, Quezon City',
                'date_of_birth' => '2006-12-04',
                'sex' => 'female',
            ],
        ];

        foreach ($users as $user) {
            User::create(array_merge($user, [
                'password' => Hash::make('password'),
                'is_active' => true,
            ]));
        }
    }
}
