<?php
/**
 * Comprehensive UserSeeder Generator with all staff and students
 * Includes: 2 admin, 2 deans, 4 pg heads, 8 instructors, 32 students
 */
$seedersPath = __DIR__ . '/database/seeders';

$userSeederContent = <<<'PHP'
<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            // Administrative Users
            [
                'email' => 'admin@cmc.edu.ph',
                'personal_email' => 'john.doe@gmail.com',
                'role' => 'it_admin',
                'official_id' => 'ADMIN001',
                'first_name' => 'John',
                'last_name' => 'Doe',
                'middle_name' => 'Smith',
                'phone' => '09-201-2345',
                'address' => '123 Main St, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901001',
                'barangay_name' => 'South Triangle',
                'date_of_birth' => '1985-05-15',
                'sex' => 'male',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=john_doe',
                'is_active' => true,
            ],
            [
                'email' => 'registrar@cmc.edu.ph',
                'personal_email' => 'pedro.cruz@gmail.com',
                'role' => 'registrar',
                'official_id' => 'REG001',
                'first_name' => 'Pedro',
                'last_name' => 'Cruz',
                'middle_name' => 'Reyes',
                'phone' => '09-161-2345',
                'address' => '789 Admin Bldg, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901002',
                'barangay_name' => 'Maginhawa',
                'date_of_birth' => '1980-03-10',
                'sex' => 'male',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=pedro_cruz',
                'is_active' => true,
            ],
            // Deans
            [
                'email' => 'dean.coecs@cmc.edu.ph',
                'personal_email' => 'maria.garcia@gmail.com',
                'role' => 'dean',
                'official_id' => 'DEAN-COECS',
                'first_name' => 'Maria',
                'last_name' => 'Garcia',
                'middle_name' => 'Santos',
                'phone' => '09-187-6543',
                'address' => '456 University Ave, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901003',
                'barangay_name' => 'Diliman',
                'date_of_birth' => '1975-08-20',
                'sex' => 'female',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria_garcia',
                'is_active' => true,
            ],
            [
                'email' => 'dean.cba@cmc.edu.ph',
                'personal_email' => 'loren.villanueva@gmail.com',
                'role' => 'dean',
                'official_id' => 'DEAN-CBA',
                'first_name' => 'Loren',
                'last_name' => 'Villanueva',
                'middle_name' => 'Reyes',
                'phone' => '09-180-0011',
                'address' => '101 Business Ave, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901004',
                'barangay_name' => 'Cubao',
                'date_of_birth' => '1973-02-12',
                'sex' => 'female',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=loren_villanueva',
                'is_active' => true,
            ],
            // Program Heads
            [
                'email' => 'ph.bsit@cmc.edu.ph',
                'personal_email' => 'ana.mendoza@gmail.com',
                'role' => 'program_head',
                'official_id' => 'PH-BSIT',
                'first_name' => 'Ana',
                'last_name' => 'Mendoza',
                'middle_name' => 'Lopez',
                'phone' => '09-171-2345',
                'address' => '321 Faculty St, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901005',
                'barangay_name' => 'Loyola Heights',
                'date_of_birth' => '1982-11-25',
                'sex' => 'female',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=ana_mendoza',
                'is_active' => true,
            ],
            [
                'email' => 'ph.bscs@cmc.edu.ph',
                'personal_email' => 'renato.sison@gmail.com',
                'role' => 'program_head',
                'official_id' => 'PH-BSCS',
                'first_name' => 'Renato',
                'last_name' => 'Sison',
                'middle_name' => 'Cruz',
                'phone' => '09-170-0222',
                'address' => '322 Faculty St, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901006',
                'barangay_name' => 'Kamias',
                'date_of_birth' => '1981-06-01',
                'sex' => 'male',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=renato_sison',
                'is_active' => true,
            ],
            [
                'email' => 'ph.bsba@cmc.edu.ph',
                'personal_email' => 'dianne.rosales@gmail.com',
                'role' => 'program_head',
                'official_id' => 'PH-BSBA',
                'first_name' => 'Dianne',
                'last_name' => 'Rosales',
                'middle_name' => 'Torres',
                'phone' => '09-170-0333',
                'address' => '201 Business Ave, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901007',
                'barangay_name' => 'Mariana',
                'date_of_birth' => '1983-04-17',
                'sex' => 'female',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=dianne_rosales',
                'is_active' => true,
            ],
            [
                'email' => 'ph.bsa@cmc.edu.ph',
                'personal_email' => 'paolo.lazaro@gmail.com',
                'role' => 'program_head',
                'official_id' => 'PH-BSA',
                'first_name' => 'Paolo',
                'last_name' => 'Lazaro',
                'middle_name' => 'Diaz',
                'phone' => '09-170-0444',
                'address' => '202 Business Ave, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901008',
                'barangay_name' => 'San Bartolome',
                'date_of_birth' => '1980-09-14',
                'sex' => 'male',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=paolo_lazaro',
                'is_active' => true,
            ],
            // Instructors - COECS
            [
                'email' => 'inst.it1@cmc.edu.ph',
                'personal_email' => 'rhea.santos@gmail.com',
                'role' => 'instructor',
                'official_id' => 'INST-IT001',
                'first_name' => 'Rhea',
                'last_name' => 'Santos',
                'middle_name' => 'Dela Cruz',
                'phone' => '09-175-5501',
                'address' => '11 Faculty St, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901009',
                'barangay_name' => 'Sikatuna',
                'date_of_birth' => '1987-01-19',
                'sex' => 'female',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=rhea_santos',
                'is_active' => true,
            ],
            [
                'email' => 'inst.it2@cmc.edu.ph',
                'personal_email' => 'marcus.reyes@gmail.com',
                'role' => 'instructor',
                'official_id' => 'INST-IT002',
                'first_name' => 'Marcus',
                'last_name' => 'Reyes',
                'middle_name' => 'Gonzales',
                'phone' => '09-175-5502',
                'address' => '13 Faculty St, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901010',
                'barangay_name' => 'Kamuning',
                'date_of_birth' => '1988-07-10',
                'sex' => 'male',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus_reyes',
                'is_active' => true,
            ],
            [
                'email' => 'inst.cs1@cmc.edu.ph',
                'personal_email' => 'armand.delgado@gmail.com',
                'role' => 'instructor',
                'official_id' => 'INST-CS001',
                'first_name' => 'Armand',
                'last_name' => 'Delgado',
                'middle_name' => 'Sy',
                'phone' => '09-175-5503',
                'address' => '12 Faculty St, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901011',
                'barangay_name' => 'UP Campus',
                'date_of_birth' => '1986-05-07',
                'sex' => 'male',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=armand_delgado',
                'is_active' => true,
            ],
            [
                'email' => 'inst.cs2@cmc.edu.ph',
                'personal_email' => 'christine.lim@gmail.com',
                'role' => 'instructor',
                'official_id' => 'INST-CS002',
                'first_name' => 'Christine',
                'last_name' => 'Lim',
                'middle_name' => 'Tolentino',
                'phone' => '09-175-5504',
                'address' => '14 Faculty St, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901012',
                'barangay_name' => 'Sta. Isabel',
                'date_of_birth' => '1989-11-28',
                'sex' => 'female',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=christine_lim',
                'is_active' => true,
            ],
            // Instructors - CBA
            [
                'email' => 'inst.ba1@cmc.edu.ph',
                'personal_email' => 'janelle.pascual@gmail.com',
                'role' => 'instructor',
                'official_id' => 'INST-BA001',
                'first_name' => 'Janelle',
                'last_name' => 'Pascual',
                'middle_name' => 'Lim',
                'phone' => '09-175-5505',
                'address' => '21 Business Ave, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901013',
                'barangay_name' => 'St. Theresa',
                'date_of_birth' => '1988-03-22',
                'sex' => 'female',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=janelle_pascual',
                'is_active' => true,
            ],
            [
                'email' => 'inst.ba2@cmc.edu.ph',
                'personal_email' => 'robert.santos@gmail.com',
                'role' => 'instructor',
                'official_id' => 'INST-BA002',
                'first_name' => 'Robert',
                'last_name' => 'Santos',
                'middle_name' => 'Fernandez',
                'phone' => '09-175-5506',
                'address' => '23 Business Ave, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901014',
                'barangay_name' => 'Sta. Cruz',
                'date_of_birth' => '1985-09-30',
                'sex' => 'male',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=robert_santos',
                'is_active' => true,
            ],
            [
                'email' => 'inst.acc1@cmc.edu.ph',
                'personal_email' => 'victor.alvarez@gmail.com',
                'role' => 'instructor',
                'official_id' => 'INST-ACC001',
                'first_name' => 'Victor',
                'last_name' => 'Alvarez',
                'middle_name' => 'Tan',
                'phone' => '09-175-5507',
                'address' => '22 Business Ave, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901015',
                'barangay_name' => 'Matalino',
                'date_of_birth' => '1984-12-02',
                'sex' => 'male',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=victor_alvarez',
                'is_active' => true,
            ],
            [
                'email' => 'inst.acc2@cmc.edu.ph',
                'personal_email' => 'vanessa.morales@gmail.com',
                'role' => 'instructor',
                'official_id' => 'INST-ACC002',
                'first_name' => 'Vanessa',
                'last_name' => 'Morales',
                'middle_name' => 'Aquino',
                'phone' => '09-175-5508',
                'address' => '24 Business Ave, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901016',
                'barangay_name' => 'Batino',
                'date_of_birth' => '1987-08-14',
                'sex' => 'female',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=vanessa_morales',
                'is_active' => true,
            ],
        ];

        // Students array
        $studentEmails = [
            // BSIT
            'student.bsit.a0@cmc.edu.ph', 'student.bsit.a1@cmc.edu.ph', 'student.bsit.a2@cmc.edu.ph', 'student.bsit.a3@cmc.edu.ph',
            'student.bsit.b0@cmc.edu.ph', 'student.bsit.b1@cmc.edu.ph', 'student.bsit.b2@cmc.edu.ph', 'student.bsit.b3@cmc.edu.ph',
            // BSCS
            'student.bscs.a0@cmc.edu.ph', 'student.bscs.a1@cmc.edu.ph', 'student.bscs.a2@cmc.edu.ph', 'student.bscs.a3@cmc.edu.ph',
            'student.bscs.b0@cmc.edu.ph', 'student.bscs.b1@cmc.edu.ph', 'student.bscs.b2@cmc.edu.ph', 'student.bscs.b3@cmc.edu.ph',
            // BSBA
            'student.bsba.a0@cmc.edu.ph', 'student.bsba.a1@cmc.edu.ph', 'student.bsba.a2@cmc.edu.ph', 'student.bsba.a3@cmc.edu.ph',
            'student.bsba.b0@cmc.edu.ph', 'student.bsba.b1@cmc.edu.ph', 'student.bsba.b2@cmc.edu.ph', 'student.bsba.b3@cmc.edu.ph',
            // BSA
            'student.bsa.a0@cmc.edu.ph', 'student.bsa.a1@cmc.edu.ph', 'student.bsa.a2@cmc.edu.ph', 'student.bsa.a3@cmc.edu.ph',
            'student.bsa.b0@cmc.edu.ph', 'student.bsa.b1@cmc.edu.ph', 'student.bsa.b2@cmc.edu.ph', 'student.bsa.b3@cmc.edu.ph',
        ];

        $studentFirstNames = ['Kyle', 'Mia', 'Noel', 'Ivy', 'Liam', 'Alyssa', 'Jared', 'Celine', 'Derek', 'Hannah',
            'Brandon', 'Sofia', 'Tyler', 'Emma', 'Jacob', 'Olivia', 'Mason', 'Ava', 'Lucas', 'Isabella',
            'Alexander', 'Mila', 'Ethan', 'Charlotte', 'Michael', 'Amelia', 'Daniel', 'Harper', 'Logan', 'Evelyn',
            'Benjamin', 'Grace'];
        $studentLastNames = ['Reyes', 'Santos', 'Garcia', 'Castro', 'Pena', 'Santiago', 'Dizon', 'Bernardo',
            'Mercado', 'Dalluran', 'Dela Cruz', 'Villanueva', 'Gutierrez', 'Ramos', 'Flores', 'Mendoza',
            'Lopez', 'Martinez', 'Torres', 'Rosales', 'Fernandez', 'Cruz', 'Hernandez', 'Rodriguez', 'Ortiz',
            'Aquino', 'Gonzales', 'Valdez', 'Robles', 'Tejada', 'Lim', 'Sy'];

        for ($i = 0; $i < count($studentEmails); $i++) {
            $fn = $studentFirstNames[$i % count($studentFirstNames)];
            $ln = $studentLastNames[$i % count($studentLastNames)];
            $year = 2005 + ($i % 2);
            $month = 1 + ($i % 12);

            $users[] = [
                'email' => $studentEmails[$i],
                'personal_email' => strtolower($fn) . '.' . strtolower($ln) . '@gmail.com',
                'role' => 'student',
                'official_id' => '2025-' . str_pad($i + 1, 4, '0', STR_PAD_LEFT),
                'first_name' => $fn,
                'last_name' => $ln,
                'middle_name' => chr(65 + ($i % 26)) . '.',
                'phone' => '09-179-' . str_pad(9001 + $i, 4, '0', STR_PAD_LEFT),
                'address' => ($i + 1) . ' Student Ave, Quezon City',
                'province_code' => '1346',
                'province_name' => 'Metro Manila',
                'city_code' => '133901',
                'city_name' => 'Quezon City',
                'barangay_code' => '133901' . str_pad(17 + ($i % 30), 3, '0', STR_PAD_LEFT),
                'barangay_name' => 'Campus Barangay ' . (($i % 15) + 1),
                'date_of_birth' => "$year-" . str_pad($month, 2, '0', STR_PAD_LEFT) . "-" . str_pad(1 + ($i % 28), 2, '0', STR_PAD_LEFT),
                'sex' => $i % 2 === 0 ? 'male' : 'female',
                'avatar' => 'https://api.dicebear.com/7.x/avataaars/svg?seed=' . strtolower($fn . '_' . $ln . '_' . ($i + 1)),
                'is_active' => true,
            ];
        }

        foreach ($users as $user) {
            User::create(array_merge($user, ['password' => Hash::make('password')]));
        }
    }
}
PHP;

// Write the file
file_put_contents($seedersPath . '/UserSeeder.php', $userSeederContent);
echo "✅ UserSeeder successfully generated with:\n";
echo "   - 2 Administrative users (Admin, Registrar)\n";
echo "   - 2 Deans (COECS, CBA)\n";
echo "   - 4 Program Heads (BSIT, BSCS, BSBA, BSA)\n";
echo "   - 8 Instructors (4 COECS, 4 CBA)\n";
echo "   - 32 Students (8 per program, 4 per block)\n";
echo "   Total: 48 users with complete data including:\n";
echo "   ✓ Personal emails\n";
echo "   ✓ Formatted phone numbers\n";
echo "   ✓ Complete address with PSGC codes\n";
echo "   ✓ Avatars (DiceBear API)\n";
echo "   ✓ All fields for testing\n\n";
?>
